# Generated by Django 6.1 on 2026-10-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("geography", "0001_initial"),
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="geography.lot",
                    ),
                ),
                (
                    "player",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location",
                        to="players.player",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departed_at", models.BigIntegerField()),
                ("arrives_at", models.BigIntegerField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("charged", models.BooleanField(default=False)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="geography.lot",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="geography.lot",
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journeys",
                        to="players.player",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["player", "completed"],
                        name="travel_jour_player__4336f8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("completed", False)),
                        fields=("player",),
                        name="journey_one_active_per_player",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("arrives_at__gt", models.F("departed_at"))),
                        name="journey_arrives_after_departure",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("origin", models.F("destination")), _negated=True
                        ),
                        name="journey_origin_differs_from_destination",
                    ),
                ],
            },
        ),
    ]
