# Generated by Django 6.1 on 2026-09-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor_real', models.DateTimeField()),
                ('anchor_game', models.BigIntegerField(default=0)),
                ('real_seconds_per_game_day', models.PositiveIntegerField(help_text='Segundos reais que duram 1 dia de jogo.')),
                ('world_processed_until', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'relógio do mundo',
                'verbose_name_plural': 'relógio do mundo',
            },
        ),
    ]
