# Generated by Django 6.1 on 2026-08-17 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroDeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia_gasta', models.PositiveSmallIntegerField()),
                ('dinheiro_ganho', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quando', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_de_trabalho', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de trabalho',
                'verbose_name_plural': 'Registros de trabalho',
                'ordering': ['-quando'],
            },
        ),
    ]
