# Generated by Django 6.1 on 2026-08-18 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrodetrabalho',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registros_de_trabalho', to='skills.categoriadehabilidade'),
        ),
        migrations.AddField(
            model_name='registrodetrabalho',
            name='xp_ganho',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
