# Generated by Django 6.1 on 2026-08-22 20:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('empresas', '0002_produto_efeito_qol_produto_nutricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='em_depressao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfil',
            name='internado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nutricao_atual',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nutricao_maxima',
            field=models.PositiveSmallIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='qol_atual',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='perfil',
            name='qol_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=4),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_sync_nutricao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_sync_qol',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ItemDoJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='em_inventario_de', to='empresas.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item do jogador',
                'verbose_name_plural': 'Itens dos jogadores',
                'ordering': ['produto__nome'],
                'unique_together': {('usuario', 'produto')},
            },
        ),
    ]
