# Generated by Django 6.1 on 2026-08-17 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='geography.estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ['nome'],
                'unique_together': {('nome', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('grid_x', models.IntegerField()),
                ('grid_y', models.IntegerField()),
                ('faixa_renda', models.CharField(choices=[('baixa', 'Baixa renda'), ('media', 'Média renda'), ('alta', 'Alta renda')], max_length=10)),
                ('qualidade_vida', models.PositiveSmallIntegerField(default=50)),
                ('e_bairro_da_prefeitura', models.BooleanField(default=False)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bairros', to='geography.cidade')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ['cidade', 'grid_y', 'grid_x'],
                'unique_together': {('cidade', 'grid_x', 'grid_y')},
            },
        ),
    ]
