# Generated by Django 6.1 on 2026-10-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('x', models.DecimalField(decimal_places=3, max_digits=12)),
                ('y', models.DecimalField(decimal_places=3, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('x', models.DecimalField(decimal_places=3, max_digits=12)),
                ('y', models.DecimalField(decimal_places=3, max_digits=12)),
                ('zoning', models.CharField(max_length=16)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='geography.city')),
            ],
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=16)),
                ('x', models.DecimalField(decimal_places=3, max_digits=12)),
                ('y', models.DecimalField(decimal_places=3, max_digits=12)),
                ('occupation', models.CharField(default='empty', max_length=16)),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='geography.neighborhood')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=16)),
                ('richness', models.DecimalField(decimal_places=3, max_digits=4)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='geography.lot')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('x', models.DecimalField(decimal_places=3, max_digits=12)),
                ('y', models.DecimalField(decimal_places=3, max_digits=12)),
                ('capital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='geography.city')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.state'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.UniqueConstraint(fields=('city', 'index'), name='neighborhood_unique_index_in_city'),
        ),
        migrations.AddConstraint(
            model_name='neighborhood',
            constraint=models.CheckConstraint(condition=models.Q(('zoning__in', ['commercial', 'industrial', 'institutional', 'residential', 'rural', 'special'])), name='neighborhood_zoning_valid'),
        ),
        migrations.AddIndex(
            model_name='lot',
            index=models.Index(fields=['category'], name='geography_l_categor_93dec7_idx'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.UniqueConstraint(fields=('neighborhood', 'index'), name='lot_unique_index_in_neighborhood'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('category__in', ['commercial', 'industrial', 'institutional', 'residential', 'rural', 'special'])), name='lot_category_valid'),
        ),
        migrations.AddConstraint(
            model_name='lot',
            constraint=models.CheckConstraint(condition=models.Q(('occupation__in', ['empty', 'occupied'])), name='lot_occupation_valid'),
        ),
        migrations.AddConstraint(
            model_name='resourcedeposit',
            constraint=models.UniqueConstraint(fields=('lot', 'resource'), name='deposit_unique_per_lot'),
        ),
        migrations.AddConstraint(
            model_name='resourcedeposit',
            constraint=models.CheckConstraint(condition=models.Q(('resource__in', ['coal', 'copper', 'diamond', 'gold', 'iron', 'lithium', 'oil', 'salt', 'silica', 'silver'])), name='deposit_resource_valid'),
        ),
        migrations.AddConstraint(
            model_name='resourcedeposit',
            constraint=models.CheckConstraint(condition=models.Q(('richness__gt', 0), ('richness__lte', 1)), name='deposit_richness_in_0_1'),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'index'), name='city_unique_index_in_state'),
        ),
    ]
