# Generated by Django 6.1 on 2026-08-20 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadeDoJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(choices=[('inteligencia', 'Inteligência'), ('fisico', 'Físico'), ('carisma', 'Carisma')], max_length=20)),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('xp_atual', models.PositiveIntegerField(default=0)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidade do jogador',
                'verbose_name_plural': 'Habilidades dos jogadores',
                'ordering': ['skill'],
                'unique_together': {('usuario', 'skill')},
            },
        ),
    ]
