# Generated by Django 6.1 on 2026-08-18 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDeHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Categoria de habilidade',
                'verbose_name_plural': 'Categorias de habilidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HabilidadeDoJogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('xp_atual', models.PositiveIntegerField(default=0)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores', to='skills.categoriadehabilidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Habilidade do jogador',
                'verbose_name_plural': 'Habilidades dos jogadores',
                'ordering': ['categoria__nome'],
                'unique_together': {('usuario', 'categoria')},
            },
        ),
    ]
