# Generated by Django 6.1 on 2026-10-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=16)),
                ('level', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'skill'), name='playerskill_unique'), models.CheckConstraint(condition=models.Q(('level__gte', 0)), name='playerskill_level_gte_0'), models.CheckConstraint(condition=models.Q(('skill__in', ['charisma', 'intelligence', 'physical'])), name='playerskill_one_of_three')],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('historic_max', models.DecimalField(decimal_places=6, default=0, max_digits=32)),
                ('last_used_day', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specializations', to='players.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('player', 'key'), name='specialization_unique'), models.CheckConstraint(condition=models.Q(('value__gte', 0)), name='specialization_value_gte_0'), models.CheckConstraint(condition=models.Q(('historic_max__gte', models.F('value'))), name='specialization_max_gte_value')],
            },
        ),
    ]
