# Generated by Django 6.1 on 2026-08-24 19:48

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0003_especializacaodofuncionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosFinanceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caixa', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('falida', models.BooleanField(default=False)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dados_financeiros', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Dados financeiros',
                'verbose_name_plural': 'Dados financeiros',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('taxa_juros', models.DecimalField(decimal_places=2, default=Decimal('0.05'), max_digits=4)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('quitado', models.BooleanField(default=False)),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.CreateModel(
            name='CartaoDeCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_devedor', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('ultima_capitalizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cartão de crédito',
                'verbose_name_plural': 'Cartões de crédito',
                'unique_together': {('usuario', 'financeira')},
            },
        ),
        migrations.CreateModel(
            name='Poupanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('ultima_capitalizacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('bloqueado_ate', models.DateTimeField(blank=True, help_text='Setado quando a Financeira quebra.', null=True)),
                ('financeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poupancas', to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poupancas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Poupança',
                'verbose_name_plural': 'Poupanças',
                'unique_together': {('usuario', 'financeira')},
            },
        ),
    ]
