# Generated by Django 6.1 on 2026-08-21 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('eh_materia_prima', models.BooleanField()),
                ('terreno_produtor', models.CharField(blank=True, choices=[('agropecuaria', 'Agropecuária'), ('extrativismo', 'Extrativismo'), ('mineracao', 'Mineração')], max_length=15, null=True)),
                ('tipo_industria_produtor', models.CharField(blank=True, choices=[('producao', 'Produção'), ('alimenticia', 'Alimentícia'), ('bens_consumo', 'Bens de consumo'), ('tecnologica', 'Tecnológica')], max_length=15, null=True)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('matriz', 'Matriz (extração/produção primária)'), ('industrial', 'Industrial (manufatura)'), ('varejo', 'Varejo (venda ao consumidor)'), ('construtora', 'Construtora'), ('servicos', 'Serviços')], max_length=12)),
                ('terreno', models.CharField(blank=True, choices=[('agropecuaria', 'Agropecuária'), ('extrativismo', 'Extrativismo'), ('mineracao', 'Mineração')], max_length=15, null=True)),
                ('tipo_industria', models.CharField(blank=True, choices=[('producao', 'Produção'), ('alimenticia', 'Alimentícia'), ('bens_consumo', 'Bens de consumo'), ('tecnologica', 'Tecnológica')], max_length=15, null=True)),
                ('especializacao_servico', models.CharField(blank=True, choices=[('transporte', 'Transporte'), ('publicidade', 'Publicidade'), ('lazer', 'Lazer'), ('financeira', 'Financeira')], max_length=15, null=True)),
                ('estrelas', models.PositiveSmallIntegerField(default=1)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas_possuidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-estrelas', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80)),
                ('skill_relevante', models.CharField(choices=[('inteligencia', 'Inteligência'), ('fisico', 'Físico'), ('carisma', 'Carisma')], max_length=20)),
                ('nivel_minimo', models.PositiveSmallIntegerField(default=0)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ocupante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargo_atual', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'ordering': ['empresa', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueDaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='empresas.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='em_estoque_de', to='empresas.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['empresa', 'produto'],
                'unique_together': {('empresa', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.PositiveIntegerField(default=1)),
                ('quantidade_produzida', models.PositiveIntegerField(default=1, help_text='Quanto de produto_final cada execução da receita rende.')),
                ('estrela_minima', models.PositiveSmallIntegerField(default=1, help_text='Estrela mínima que a Industrial precisa ter pra fabricar esse produto.')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usado_em_receitas', to='empresas.produto')),
                ('produto_final', models.ForeignKey(limit_choices_to={'eh_materia_prima': False}, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='empresas.produto')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'unique_together': {('produto_final', 'ingrediente')},
            },
        ),
    ]
