# Generated by Django 6.1 on 2026-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='efeito_qol',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='produto',
            name='nutricao',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
