# Generated by Django 6.1 on 2026-08-19 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('matriz', 'Matriz (extração/produção primária)'), ('industrial', 'Industrial (manufatura)'), ('varejo', 'Varejo (venda ao consumidor)')], default='varejo', max_length=12),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('eh_materia_prima', models.BooleanField()),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='skills.categoriadehabilidade')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['setor', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EstoqueDaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='empresas.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='em_estoque_de', to='empresas.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'ordering': ['empresa', 'produto'],
                'unique_together': {('empresa', 'produto')},
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.PositiveIntegerField(default=1)),
                ('quantidade_produzida', models.PositiveIntegerField(default=1, help_text='Quanto de produto_final cada execução da receita rende.')),
                ('materia_prima', models.ForeignKey(limit_choices_to={'eh_materia_prima': True}, on_delete=django.db.models.deletion.PROTECT, related_name='usada_em_receitas', to='empresas.produto')),
                ('produto_final', models.ForeignKey(limit_choices_to={'eh_materia_prima': False}, on_delete=django.db.models.deletion.CASCADE, related_name='receitas', to='empresas.produto')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
                'unique_together': {('produto_final', 'materia_prima')},
            },
        ),
    ]
