# Generated by Django 6.1 on 2026-08-23 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_produto_efeito_qol_produto_nutricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecializacaoDoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.PositiveSmallIntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especialistas', to='empresas.produto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especializacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Especialização de funcionário',
                'verbose_name_plural': 'Especializações de funcionários',
                'unique_together': {('usuario', 'produto')},
            },
        ),
    ]
