# Generated by Django 6.1 on 2026-08-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_empresa_tipo_produto_estoquedaempresa_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tipo',
            field=models.CharField(choices=[('matriz', 'Matriz (extração/produção primária)'), ('industrial', 'Industrial (manufatura)'), ('varejo', 'Varejo (venda ao consumidor)'), ('construtora', 'Construtora')], default='varejo', max_length=12),
        ),
    ]
