# Generated by Django 6.1 on 2026-10-01 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=6, max_digits=14)),
                ('health', models.DecimalField(decimal_places=6, max_digits=14)),
                ('nutrition', models.DecimalField(decimal_places=6, max_digits=14)),
                ('burnout', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('burnout_active', models.BooleanField(default=False)),
                ('health_critical', models.BooleanField(default=False)),
                ('hospitalized_until', models.BigIntegerField(blank=True, null=True)),
                ('last_work_at', models.BigIntegerField(blank=True, null=True)),
                ('processed_until', models.BigIntegerField()),
                ('created_at_game', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QolEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=32)),
                ('source', models.CharField(help_text="Origem do efeito (ex.: 'food:chocolate').", max_length=64)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=10)),
                ('starts_at', models.BigIntegerField()),
                ('expires_at', models.BigIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qol_effects', to='players.player')),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('energy__gte', 0)), name='player_energy_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('health__gte', 0)), name='player_health_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('nutrition__gte', 0)), name='player_nutrition_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.CheckConstraint(condition=models.Q(('burnout__gte', 0)), name='player_burnout_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='qoleffect',
            constraint=models.UniqueConstraint(fields=('player', 'category'), name='qoleffect_one_per_category'),
        ),
        migrations.AddConstraint(
            model_name='qoleffect',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('starts_at'))), name='qoleffect_expires_after_start'),
        ),
    ]
